GET http://localhost:3000/character_coordinate

###

POST http://localhost:3000/game/easy/waldo
Content-Type: application/json

{
    "x": 861,
    "y": 921
}


###
POST http://localhost:3000/leaderboard
Content-Type: application/json

{
    "name": "trial2",
    "duration": {
        "seconds" : 32,
        "minutes": 53, 
        "total_seconds": 5
    },
    "difficulty":"hard"
}

###
GET http://localhost:3000/leaderboard

###
GET http://localhost:3000/game/easy/hint